name: Publish npm Package and Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: hashicorp/vault-action@2c5827061f1ad91ca97897d6257ebe638e033699
        with:
          method: jwt
          path: jwt-github-actions
          role: github-issuu-issuu-api-sdk
          url: https://vault.bendingspoons.com
          secrets: |
              static2/data/github/issuu/issuu-api-sdk/manual NPM_CI_TOKEN

      - name: Checkout Repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install Dependencies
        run: npm install

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_CI_TOKEN }}

      - name: Publish Package
        run: npm publish --access public

